version: '3.8'

services:
  node-api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: node-notion
    restart: on-failure
    expose:
      - 3000
    ports:
      - 3000:3000
    command: pnpm dev
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    env_file:
      - .env
